/* Shared skill dictionary. Browser: window.ATS_SKILLS. Node: require('./skills-data'). */
(function (root, factory) {
  if (typeof module === "object" && module.exports) module.exports = factory();
  else root.ATS_SKILLS = factory();
})(typeof self !== "undefined" ? self : this, function () {
  return [
    "javascript",
    "react",
    "node",
    "express",
    "mongodb",
    "mysql",
    "java",
    "spring",
    "spring boot",
    "hibernate",
    "junit",
    "maven",
    "flask",
    "python",
    "django",
    "html",
    "css",
    "git",
    "github",
    "docker",
    "aws",
    "kubernetes",
    "typescript",
    "c++",
    "sql",
    "php",
    "laravel",
    "angular",
    "vue",
    "next.js",
    "nextjs",
    "scrum",
    "agile",
    "jira",
    "android",
    "ios",
    "swift",
    "kotlin",
    "devops",
    "ci/cd",
    "machine learning",
    "c#",
    ".net",
    "dotnet",
    "postgresql",
    "redis",
    "firebase",
    "graphql",
    "tailwind",
    "bootstrap",
    "jquery",
    "redux",
    "figma",
    "terraform",
    "azure",
    "gcp",
    "linux",
    "project management",
    "salesforce",
    "excel",
    "sql server",
    "nosql",
    "microservices",
    "html5",
    "css3",
    "sass",
    "webpack",
    "jenkins",
    "ansible",

    // Additional common data/AI skills
    "pandas",
    "numpy",
    "scikit-learn",
    "sklearn",
    "matplotlib",
    "seaborn",
    "tensorflow",
    "pytorch",
    "keras",
    "opencv",
    "power bi",
    "tableau",

    // AI/ML terms that previously only surfaced (unreliably) via signal-phrase
    // or capitalized-word detection. "js" is deliberately NOT added as a bare
    // alias: resumes that list project files (app.js, engine.js) would match
    // "\bjs\b" on the file extension itself, since a preceding "." still
    // counts as a word boundary. "javascript" (already above) still matches.
    "artificial intelligence",
    "nlp",
    "llm",
    "rag",
    "langchain",
    "hugging face",
    "fastapi",
    "openai",
    "generative ai",
    "prompt engineering",
    "vector database",
    "rest api",
    "api",
    "kafka", "rabbitmq", "redis streams", "oracle", "pl/sql", "sqlite",
    "jest", "vitest", "cypress", "playwright", "selenium", "storybook",
    "golang", "go", "rust", "ruby", "rails", "spring security", "spring cloud",
    "elasticsearch", "snowflake", "databricks", "airflow", "spark", "hadoop",
    "graphql", "websocket", "oauth", "jwt", "linux administration", "bash",
  ];
});
